"""add proveedor & rename impuesto_compra

Revision ID: 1c50c7a51c89
Revises: bf61e8930d28
Create Date: 2025-08-31 10:50:02.453753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c50c7a51c89'
down_revision: Union[str, Sequence[str], None] = 'bf61e8930d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('proveedor', sa.Integer(), nullable=True))
    op.add_column(
        'Product',
        sa.Column('tipo_producto', sa.Integer(), server_default='1', nullable=False)
    )
    op.alter_column('Product', 'tipo_producto', server_default=None)
    op.add_column('Product', sa.Column('maneja_inventario', sa.Boolean(), nullable=False))
    op.add_column('Product', sa.Column('stock_minimo', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('Product', sa.Column('precio_venta', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('Product', sa.Column('impuesto_venta', sa.Integer(), nullable=True))
    op.add_column('Product', sa.Column('impuesto_compra', sa.Integer(), nullable=True))
    op.add_column('Product', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('Product', sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('Product', 'stockMinimo')
    op.drop_column('Product', 'tipoProducto')
    op.drop_column('Product', 'precioVenta')
    op.drop_column('Product', 'fechaActualizacion')
    op.drop_column('Product', 'manejaInventario')
    op.drop_column('Product', 'impuestoCompra')
    op.drop_column('Product', 'fechaCreacion')
    op.drop_column('Product', 'impuestoVenta')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Product', sa.Column('impuestoVenta', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Product', sa.Column('fechaCreacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('Product', sa.Column('impuestoCompra', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Product', sa.Column('manejaInventario', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('Product', sa.Column('fechaActualizacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('Product', sa.Column('precioVenta', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.add_column('Product', sa.Column('tipoProducto', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('Product', sa.Column('stockMinimo', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False))
    op.drop_column('Product', 'fecha_actualizacion')
    op.drop_column('Product', 'fecha_creacion')
    op.drop_column('Product', 'impuesto_compra')
    op.drop_column('Product', 'impuesto_venta')
    op.drop_column('Product', 'precio_venta')
    op.drop_column('Product', 'stock_minimo')
    op.drop_column('Product', 'maneja_inventario')
    op.drop_column('Product', 'tipo_producto')
    op.drop_column('Product', 'proveedor')
    # ### end Alembic commands ###
